server:
  servlet:
    context-path: ${CONTEXT_PATH:/madoi}

logging:
  level:
    org:
      springframework:
#        security: TRACE

madoi:
  adminUser: madoiadmin
  adminPass: sdfj3osadkvc
  authTokens:
    - ${MADOI_AUTH_TOKENS}
  allowedOrigins:
    - ${MADOI_ALLOWED_ORIGINS:http://localhost:[*]}
  websocket:
    maxTextMessageBufferSize: ${MADOI_WEBSOCKET_MAXTEXTMESSAGEBUFFERSIZE:10485760}  # 10 * 1024 * 1024
    maxBinaryMessageBufferSize: ${MADOI_WEBSOCKET_MAXBINARYMESSAGEBUFFERSIZE:10485760}  # 10 * 1024 * 1024
  skyWay:
    appId: ${SKYWAY_APP_ID:YOUR_SKYWAY_ID}
    secret: ${SKYWAY_SECRET:YOUR_SKYWAY_SECRET}

