server:
  servlet:
    context-path: ${CONTEXT_PATH:/madoi}

logging:
  level:
    org:
      springframework:
#        security: TRACE

madoi:
  authTokens:
    - ${MADOI_AUTH_TOKENS}
  allowedOrigins:
    - ${MADOI_ALLOWED_ORIGINS}
  websocket:
    maxTextMessageBufferSize: ${MADOI_WEBSOCKET_MAXTEXTMESSAGEBUFFERSIZE:10485760}  # 10 * 1024 * 1024
    maxBinaryMessageBufferSize: ${MADOI_WEBSOCKET_MAXBINARYMESSAGEBUFFERSIZE:10485760}  # 10 * 1024 * 1024

