server:
  servlet:
    context-path: ${CONTEXT_PATH:/madoi}

logging:
  level:
    org:
      springframework:
#        security: TRACE

madoi:
  apiKeys:
    - ${MADOI_API_KEY:SheiYo8cohg0quei}
  allowedOrigins:
    - ${MADOI_ALLOWED_ORIGIN:http://localhost:[*]}
  websocket:
    maxTextMessageBufferSize: ${MADOI_WEBSOCKET_MAXTEXTMESSAGEBUFFERSIZE:10485760}  # 10 * 1024 * 1024
    maxBinaryMessageBufferSize: ${MADOI_WEBSOCKET_MAXBINARYMESSAGEBUFFERSIZE:10485760}  # 10 * 1024 * 1024

