services:
  madoi_volatileserver:
    build: .
    ports:
      - 8080:8080
    environment:
      MADOI_API_KEY: ahfuTep6ooDi7Oa4
      MADOI_ALLOWED_ORIGIN: http://localhost:[*]
      MADOI_WEBSOCKET_MAXTEXTMESSAGEBUFFERSIZE: 10485760  # 10 * 1024 * 1024
      MADOI_WEBSOCKET_MAXBINARYMESSAGEBUFFERSIZE: 10485760  # 10 * 1024 * 1024
